workflow:
  rules:
    # This is needed for merge trains
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # This is needed to run in MRs
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - ci

# Use pytest to run unit-tests
ci:unit-tests:
  stage: ci
  image:
    name: ghcr.io/astral-sh/uv:python3.9-bookworm-slim
  script:
    - uv sync
    - uv run run_presubmit.py test
  tags:
    - cpu

# Run linters, autoformat checks, type checks.
ci:lint:
  stage: ci
  image:
    name: ghcr.io/astral-sh/uv:python3.9-bookworm-slim
  script:
    - uv sync
    - uv run run_presubmit.py lint
  tags:
    - cpu

