on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to test release for'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract changelog section for tag
        id: extract
        run: |
          TAG="${{ github.event.inputs.tag || github.ref_name }}"
          TAG=${TAG#v}  # Strip leading 'v' if present
          echo "Looking for changelog section for tag: $TAG"

          # Extract relevant section
          CHANGELOG=$(awk -v tag="$TAG" '
            $0 ~ "## \\[" tag "\\]" {flag=1; next}
            flag && /^## \[/ {flag=0}
            flag && /^### Released/ {next}
            flag && /^- [0-9]{4}-[0-9]{2}-[0-9]{2}/ {next}
            flag {print}
          ' CHANGELOG.md)

          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="No changelog entry found for $TAG"
          fi

          # Write to a temp file
          echo "$CHANGELOG" > release_notes.md

          # Save multiline output to GITHUB_ENV via file
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
